version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: avito_tech-client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: avito_tech-server
    ports:
      - "8000:8000"
